// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/error.proto

// Protobuf Java Version: 3.25.3
package d_engine.error;

public final class Error {
  private Error() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code d_engine.error.ErrorCode}
   */
  public enum ErrorCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Success status (non-error)
     * </pre>
     *
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <pre>
     * ======================
     * Network layer error (1000-1999)
     * ======================
     * </pre>
     *
     * <code>CONNECTION_TIMEOUT = 1001;</code>
     */
    CONNECTION_TIMEOUT(1001),
    /**
     * <code>INVALID_ADDRESS = 1002;</code>
     */
    INVALID_ADDRESS(1002),
    /**
     * <code>LEADER_CHANGED = 1003;</code>
     */
    LEADER_CHANGED(1003),
    /**
     * <code>JOIN_ERROR = 1004;</code>
     */
    JOIN_ERROR(1004),
    /**
     * <pre>
     * ======================
     * Protocol layer error (2000-2999)
     * ======================
     * </pre>
     *
     * <code>INVALID_RESPONSE = 2001;</code>
     */
    INVALID_RESPONSE(2001),
    /**
     * <code>VERSION_MISMATCH = 2002;</code>
     */
    VERSION_MISMATCH(2002),
    /**
     * <pre>
     * ======================
     * Storage layer error (3000-3999)
     * ======================
     * </pre>
     *
     * <code>DISK_FULL = 3001;</code>
     */
    DISK_FULL(3001),
    /**
     * <code>DATA_CORRUPTION = 3002;</code>
     */
    DATA_CORRUPTION(3002),
    /**
     * <code>STORAGE_IO_ERROR = 3003;</code>
     */
    STORAGE_IO_ERROR(3003),
    /**
     * <code>STORAGE_PERMISSION_DENIED = 3004;</code>
     */
    STORAGE_PERMISSION_DENIED(3004),
    /**
     * <code>KEY_NOT_EXIST = 3005;</code>
     */
    KEY_NOT_EXIST(3005),
    /**
     * <pre>
     * ======================
     * Business logic error (4000-4999)
     * ======================
     * </pre>
     *
     * <code>NOT_LEADER = 4001;</code>
     */
    NOT_LEADER(4001),
    /**
     * <code>STALE_OPERATION = 4002;</code>
     */
    STALE_OPERATION(4002),
    /**
     * <code>INVALID_REQUEST = 4003;</code>
     */
    INVALID_REQUEST(4003),
    /**
     * <code>RATE_LIMITED = 4004;</code>
     */
    RATE_LIMITED(4004),
    /**
     * <code>CLUSTER_UNAVAILABLE = 4005;</code>
     */
    CLUSTER_UNAVAILABLE(4005),
    /**
     * <code>PROPOSE_FAILED = 4006;</code>
     */
    PROPOSE_FAILED(4006),
    /**
     * <code>TERM_OUTDATED = 4007;</code>
     */
    TERM_OUTDATED(4007),
    /**
     * <code>RETRY_REQUIRED = 4008;</code>
     */
    RETRY_REQUIRED(4008),
    /**
     * <pre>
     * ======================
     * Unclassified error
     * ======================
     * </pre>
     *
     * <code>GENERAL = 8888;</code>
     */
    GENERAL(8888),
    /**
     * <code>UNCATEGORIZED = 9999;</code>
     */
    UNCATEGORIZED(9999),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Success status (non-error)
     * </pre>
     *
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <pre>
     * ======================
     * Network layer error (1000-1999)
     * ======================
     * </pre>
     *
     * <code>CONNECTION_TIMEOUT = 1001;</code>
     */
    public static final int CONNECTION_TIMEOUT_VALUE = 1001;
    /**
     * <code>INVALID_ADDRESS = 1002;</code>
     */
    public static final int INVALID_ADDRESS_VALUE = 1002;
    /**
     * <code>LEADER_CHANGED = 1003;</code>
     */
    public static final int LEADER_CHANGED_VALUE = 1003;
    /**
     * <code>JOIN_ERROR = 1004;</code>
     */
    public static final int JOIN_ERROR_VALUE = 1004;
    /**
     * <pre>
     * ======================
     * Protocol layer error (2000-2999)
     * ======================
     * </pre>
     *
     * <code>INVALID_RESPONSE = 2001;</code>
     */
    public static final int INVALID_RESPONSE_VALUE = 2001;
    /**
     * <code>VERSION_MISMATCH = 2002;</code>
     */
    public static final int VERSION_MISMATCH_VALUE = 2002;
    /**
     * <pre>
     * ======================
     * Storage layer error (3000-3999)
     * ======================
     * </pre>
     *
     * <code>DISK_FULL = 3001;</code>
     */
    public static final int DISK_FULL_VALUE = 3001;
    /**
     * <code>DATA_CORRUPTION = 3002;</code>
     */
    public static final int DATA_CORRUPTION_VALUE = 3002;
    /**
     * <code>STORAGE_IO_ERROR = 3003;</code>
     */
    public static final int STORAGE_IO_ERROR_VALUE = 3003;
    /**
     * <code>STORAGE_PERMISSION_DENIED = 3004;</code>
     */
    public static final int STORAGE_PERMISSION_DENIED_VALUE = 3004;
    /**
     * <code>KEY_NOT_EXIST = 3005;</code>
     */
    public static final int KEY_NOT_EXIST_VALUE = 3005;
    /**
     * <pre>
     * ======================
     * Business logic error (4000-4999)
     * ======================
     * </pre>
     *
     * <code>NOT_LEADER = 4001;</code>
     */
    public static final int NOT_LEADER_VALUE = 4001;
    /**
     * <code>STALE_OPERATION = 4002;</code>
     */
    public static final int STALE_OPERATION_VALUE = 4002;
    /**
     * <code>INVALID_REQUEST = 4003;</code>
     */
    public static final int INVALID_REQUEST_VALUE = 4003;
    /**
     * <code>RATE_LIMITED = 4004;</code>
     */
    public static final int RATE_LIMITED_VALUE = 4004;
    /**
     * <code>CLUSTER_UNAVAILABLE = 4005;</code>
     */
    public static final int CLUSTER_UNAVAILABLE_VALUE = 4005;
    /**
     * <code>PROPOSE_FAILED = 4006;</code>
     */
    public static final int PROPOSE_FAILED_VALUE = 4006;
    /**
     * <code>TERM_OUTDATED = 4007;</code>
     */
    public static final int TERM_OUTDATED_VALUE = 4007;
    /**
     * <code>RETRY_REQUIRED = 4008;</code>
     */
    public static final int RETRY_REQUIRED_VALUE = 4008;
    /**
     * <pre>
     * ======================
     * Unclassified error
     * ======================
     * </pre>
     *
     * <code>GENERAL = 8888;</code>
     */
    public static final int GENERAL_VALUE = 8888;
    /**
     * <code>UNCATEGORIZED = 9999;</code>
     */
    public static final int UNCATEGORIZED_VALUE = 9999;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ErrorCode valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static ErrorCode forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1001: return CONNECTION_TIMEOUT;
        case 1002: return INVALID_ADDRESS;
        case 1003: return LEADER_CHANGED;
        case 1004: return JOIN_ERROR;
        case 2001: return INVALID_RESPONSE;
        case 2002: return VERSION_MISMATCH;
        case 3001: return DISK_FULL;
        case 3002: return DATA_CORRUPTION;
        case 3003: return STORAGE_IO_ERROR;
        case 3004: return STORAGE_PERMISSION_DENIED;
        case 3005: return KEY_NOT_EXIST;
        case 4001: return NOT_LEADER;
        case 4002: return STALE_OPERATION;
        case 4003: return INVALID_REQUEST;
        case 4004: return RATE_LIMITED;
        case 4005: return CLUSTER_UNAVAILABLE;
        case 4006: return PROPOSE_FAILED;
        case 4007: return TERM_OUTDATED;
        case 4008: return RETRY_REQUIRED;
        case 8888: return GENERAL;
        case 9999: return UNCATEGORIZED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ErrorCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ErrorCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ErrorCode>() {
            public ErrorCode findValueByNumber(int number) {
              return ErrorCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return d_engine.error.Error.getDescriptor().getEnumTypes().get(0);
    }

    private static final ErrorCode[] VALUES = values();

    public static ErrorCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ErrorCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:d_engine.error.ErrorCode)
  }

  public interface ErrorMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:d_engine.error.ErrorMetadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Errors suitable for retry
     * </pre>
     *
     * <code>optional uint64 retry_after_ms = 1;</code>
     * @return Whether the retryAfterMs field is set.
     */
    boolean hasRetryAfterMs();
    /**
     * <pre>
     * Errors suitable for retry
     * </pre>
     *
     * <code>optional uint64 retry_after_ms = 1;</code>
     * @return The retryAfterMs.
     */
    long getRetryAfterMs();

    /**
     * <pre>
     * Leader change information
     * </pre>
     *
     * <code>optional string leader_id = 2;</code>
     * @return Whether the leaderId field is set.
     */
    boolean hasLeaderId();
    /**
     * <pre>
     * Leader change information
     * </pre>
     *
     * <code>optional string leader_id = 2;</code>
     * @return The leaderId.
     */
    java.lang.String getLeaderId();
    /**
     * <pre>
     * Leader change information
     * </pre>
     *
     * <code>optional string leader_id = 2;</code>
     * @return The bytes for leaderId.
     */
    com.google.protobuf.ByteString
        getLeaderIdBytes();

    /**
     * <code>optional string leader_address = 3;</code>
     * @return Whether the leaderAddress field is set.
     */
    boolean hasLeaderAddress();
    /**
     * <code>optional string leader_address = 3;</code>
     * @return The leaderAddress.
     */
    java.lang.String getLeaderAddress();
    /**
     * <code>optional string leader_address = 3;</code>
     * @return The bytes for leaderAddress.
     */
    com.google.protobuf.ByteString
        getLeaderAddressBytes();

    /**
     * <pre>
     * Error details (for debugging only)
     * </pre>
     *
     * <code>optional string debug_message = 15;</code>
     * @return Whether the debugMessage field is set.
     */
    boolean hasDebugMessage();
    /**
     * <pre>
     * Error details (for debugging only)
     * </pre>
     *
     * <code>optional string debug_message = 15;</code>
     * @return The debugMessage.
     */
    java.lang.String getDebugMessage();
    /**
     * <pre>
     * Error details (for debugging only)
     * </pre>
     *
     * <code>optional string debug_message = 15;</code>
     * @return The bytes for debugMessage.
     */
    com.google.protobuf.ByteString
        getDebugMessageBytes();
  }
  /**
   * Protobuf type {@code d_engine.error.ErrorMetadata}
   */
  public static final class ErrorMetadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:d_engine.error.ErrorMetadata)
      ErrorMetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ErrorMetadata.newBuilder() to construct.
    private ErrorMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ErrorMetadata() {
      leaderId_ = "";
      leaderAddress_ = "";
      debugMessage_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ErrorMetadata();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return d_engine.error.Error.internal_static_d_engine_error_ErrorMetadata_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return d_engine.error.Error.internal_static_d_engine_error_ErrorMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              d_engine.error.Error.ErrorMetadata.class, d_engine.error.Error.ErrorMetadata.Builder.class);
    }

    private int bitField0_;
    public static final int RETRY_AFTER_MS_FIELD_NUMBER = 1;
    private long retryAfterMs_ = 0L;
    /**
     * <pre>
     * Errors suitable for retry
     * </pre>
     *
     * <code>optional uint64 retry_after_ms = 1;</code>
     * @return Whether the retryAfterMs field is set.
     */
    @java.lang.Override
    public boolean hasRetryAfterMs() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Errors suitable for retry
     * </pre>
     *
     * <code>optional uint64 retry_after_ms = 1;</code>
     * @return The retryAfterMs.
     */
    @java.lang.Override
    public long getRetryAfterMs() {
      return retryAfterMs_;
    }

    public static final int LEADER_ID_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object leaderId_ = "";
    /**
     * <pre>
     * Leader change information
     * </pre>
     *
     * <code>optional string leader_id = 2;</code>
     * @return Whether the leaderId field is set.
     */
    @java.lang.Override
    public boolean hasLeaderId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Leader change information
     * </pre>
     *
     * <code>optional string leader_id = 2;</code>
     * @return The leaderId.
     */
    @java.lang.Override
    public java.lang.String getLeaderId() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Leader change information
     * </pre>
     *
     * <code>optional string leader_id = 2;</code>
     * @return The bytes for leaderId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLeaderIdBytes() {
      java.lang.Object ref = leaderId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEADER_ADDRESS_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object leaderAddress_ = "";
    /**
     * <code>optional string leader_address = 3;</code>
     * @return Whether the leaderAddress field is set.
     */
    @java.lang.Override
    public boolean hasLeaderAddress() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string leader_address = 3;</code>
     * @return The leaderAddress.
     */
    @java.lang.Override
    public java.lang.String getLeaderAddress() {
      java.lang.Object ref = leaderAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        leaderAddress_ = s;
        return s;
      }
    }
    /**
     * <code>optional string leader_address = 3;</code>
     * @return The bytes for leaderAddress.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLeaderAddressBytes() {
      java.lang.Object ref = leaderAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        leaderAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEBUG_MESSAGE_FIELD_NUMBER = 15;
    @SuppressWarnings("serial")
    private volatile java.lang.Object debugMessage_ = "";
    /**
     * <pre>
     * Error details (for debugging only)
     * </pre>
     *
     * <code>optional string debug_message = 15;</code>
     * @return Whether the debugMessage field is set.
     */
    @java.lang.Override
    public boolean hasDebugMessage() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Error details (for debugging only)
     * </pre>
     *
     * <code>optional string debug_message = 15;</code>
     * @return The debugMessage.
     */
    @java.lang.Override
    public java.lang.String getDebugMessage() {
      java.lang.Object ref = debugMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        debugMessage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Error details (for debugging only)
     * </pre>
     *
     * <code>optional string debug_message = 15;</code>
     * @return The bytes for debugMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDebugMessageBytes() {
      java.lang.Object ref = debugMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        debugMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt64(1, retryAfterMs_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, leaderId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, leaderAddress_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 15, debugMessage_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, retryAfterMs_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, leaderId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, leaderAddress_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, debugMessage_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof d_engine.error.Error.ErrorMetadata)) {
        return super.equals(obj);
      }
      d_engine.error.Error.ErrorMetadata other = (d_engine.error.Error.ErrorMetadata) obj;

      if (hasRetryAfterMs() != other.hasRetryAfterMs()) return false;
      if (hasRetryAfterMs()) {
        if (getRetryAfterMs()
            != other.getRetryAfterMs()) return false;
      }
      if (hasLeaderId() != other.hasLeaderId()) return false;
      if (hasLeaderId()) {
        if (!getLeaderId()
            .equals(other.getLeaderId())) return false;
      }
      if (hasLeaderAddress() != other.hasLeaderAddress()) return false;
      if (hasLeaderAddress()) {
        if (!getLeaderAddress()
            .equals(other.getLeaderAddress())) return false;
      }
      if (hasDebugMessage() != other.hasDebugMessage()) return false;
      if (hasDebugMessage()) {
        if (!getDebugMessage()
            .equals(other.getDebugMessage())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRetryAfterMs()) {
        hash = (37 * hash) + RETRY_AFTER_MS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRetryAfterMs());
      }
      if (hasLeaderId()) {
        hash = (37 * hash) + LEADER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getLeaderId().hashCode();
      }
      if (hasLeaderAddress()) {
        hash = (37 * hash) + LEADER_ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getLeaderAddress().hashCode();
      }
      if (hasDebugMessage()) {
        hash = (37 * hash) + DEBUG_MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getDebugMessage().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static d_engine.error.Error.ErrorMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static d_engine.error.Error.ErrorMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static d_engine.error.Error.ErrorMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static d_engine.error.Error.ErrorMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static d_engine.error.Error.ErrorMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static d_engine.error.Error.ErrorMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static d_engine.error.Error.ErrorMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static d_engine.error.Error.ErrorMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static d_engine.error.Error.ErrorMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static d_engine.error.Error.ErrorMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static d_engine.error.Error.ErrorMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static d_engine.error.Error.ErrorMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(d_engine.error.Error.ErrorMetadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code d_engine.error.ErrorMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:d_engine.error.ErrorMetadata)
        d_engine.error.Error.ErrorMetadataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return d_engine.error.Error.internal_static_d_engine_error_ErrorMetadata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return d_engine.error.Error.internal_static_d_engine_error_ErrorMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                d_engine.error.Error.ErrorMetadata.class, d_engine.error.Error.ErrorMetadata.Builder.class);
      }

      // Construct using d_engine.error.Error.ErrorMetadata.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        retryAfterMs_ = 0L;
        leaderId_ = "";
        leaderAddress_ = "";
        debugMessage_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return d_engine.error.Error.internal_static_d_engine_error_ErrorMetadata_descriptor;
      }

      @java.lang.Override
      public d_engine.error.Error.ErrorMetadata getDefaultInstanceForType() {
        return d_engine.error.Error.ErrorMetadata.getDefaultInstance();
      }

      @java.lang.Override
      public d_engine.error.Error.ErrorMetadata build() {
        d_engine.error.Error.ErrorMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public d_engine.error.Error.ErrorMetadata buildPartial() {
        d_engine.error.Error.ErrorMetadata result = new d_engine.error.Error.ErrorMetadata(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(d_engine.error.Error.ErrorMetadata result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.retryAfterMs_ = retryAfterMs_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.leaderId_ = leaderId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.leaderAddress_ = leaderAddress_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.debugMessage_ = debugMessage_;
          to_bitField0_ |= 0x00000008;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof d_engine.error.Error.ErrorMetadata) {
          return mergeFrom((d_engine.error.Error.ErrorMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(d_engine.error.Error.ErrorMetadata other) {
        if (other == d_engine.error.Error.ErrorMetadata.getDefaultInstance()) return this;
        if (other.hasRetryAfterMs()) {
          setRetryAfterMs(other.getRetryAfterMs());
        }
        if (other.hasLeaderId()) {
          leaderId_ = other.leaderId_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasLeaderAddress()) {
          leaderAddress_ = other.leaderAddress_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasDebugMessage()) {
          debugMessage_ = other.debugMessage_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                retryAfterMs_ = input.readUInt64();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                leaderId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                leaderAddress_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 122: {
                debugMessage_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 122
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private long retryAfterMs_ ;
      /**
       * <pre>
       * Errors suitable for retry
       * </pre>
       *
       * <code>optional uint64 retry_after_ms = 1;</code>
       * @return Whether the retryAfterMs field is set.
       */
      @java.lang.Override
      public boolean hasRetryAfterMs() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <pre>
       * Errors suitable for retry
       * </pre>
       *
       * <code>optional uint64 retry_after_ms = 1;</code>
       * @return The retryAfterMs.
       */
      @java.lang.Override
      public long getRetryAfterMs() {
        return retryAfterMs_;
      }
      /**
       * <pre>
       * Errors suitable for retry
       * </pre>
       *
       * <code>optional uint64 retry_after_ms = 1;</code>
       * @param value The retryAfterMs to set.
       * @return This builder for chaining.
       */
      public Builder setRetryAfterMs(long value) {

        retryAfterMs_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Errors suitable for retry
       * </pre>
       *
       * <code>optional uint64 retry_after_ms = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearRetryAfterMs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        retryAfterMs_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object leaderId_ = "";
      /**
       * <pre>
       * Leader change information
       * </pre>
       *
       * <code>optional string leader_id = 2;</code>
       * @return Whether the leaderId field is set.
       */
      public boolean hasLeaderId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Leader change information
       * </pre>
       *
       * <code>optional string leader_id = 2;</code>
       * @return The leaderId.
       */
      public java.lang.String getLeaderId() {
        java.lang.Object ref = leaderId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          leaderId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Leader change information
       * </pre>
       *
       * <code>optional string leader_id = 2;</code>
       * @return The bytes for leaderId.
       */
      public com.google.protobuf.ByteString
          getLeaderIdBytes() {
        java.lang.Object ref = leaderId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Leader change information
       * </pre>
       *
       * <code>optional string leader_id = 2;</code>
       * @param value The leaderId to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        leaderId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Leader change information
       * </pre>
       *
       * <code>optional string leader_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderId() {
        leaderId_ = getDefaultInstance().getLeaderId();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Leader change information
       * </pre>
       *
       * <code>optional string leader_id = 2;</code>
       * @param value The bytes for leaderId to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        leaderId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object leaderAddress_ = "";
      /**
       * <code>optional string leader_address = 3;</code>
       * @return Whether the leaderAddress field is set.
       */
      public boolean hasLeaderAddress() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string leader_address = 3;</code>
       * @return The leaderAddress.
       */
      public java.lang.String getLeaderAddress() {
        java.lang.Object ref = leaderAddress_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          leaderAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string leader_address = 3;</code>
       * @return The bytes for leaderAddress.
       */
      public com.google.protobuf.ByteString
          getLeaderAddressBytes() {
        java.lang.Object ref = leaderAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          leaderAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string leader_address = 3;</code>
       * @param value The leaderAddress to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderAddress(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        leaderAddress_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional string leader_address = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLeaderAddress() {
        leaderAddress_ = getDefaultInstance().getLeaderAddress();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>optional string leader_address = 3;</code>
       * @param value The bytes for leaderAddress to set.
       * @return This builder for chaining.
       */
      public Builder setLeaderAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        leaderAddress_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object debugMessage_ = "";
      /**
       * <pre>
       * Error details (for debugging only)
       * </pre>
       *
       * <code>optional string debug_message = 15;</code>
       * @return Whether the debugMessage field is set.
       */
      public boolean hasDebugMessage() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * Error details (for debugging only)
       * </pre>
       *
       * <code>optional string debug_message = 15;</code>
       * @return The debugMessage.
       */
      public java.lang.String getDebugMessage() {
        java.lang.Object ref = debugMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          debugMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Error details (for debugging only)
       * </pre>
       *
       * <code>optional string debug_message = 15;</code>
       * @return The bytes for debugMessage.
       */
      public com.google.protobuf.ByteString
          getDebugMessageBytes() {
        java.lang.Object ref = debugMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          debugMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Error details (for debugging only)
       * </pre>
       *
       * <code>optional string debug_message = 15;</code>
       * @param value The debugMessage to set.
       * @return This builder for chaining.
       */
      public Builder setDebugMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        debugMessage_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Error details (for debugging only)
       * </pre>
       *
       * <code>optional string debug_message = 15;</code>
       * @return This builder for chaining.
       */
      public Builder clearDebugMessage() {
        debugMessage_ = getDefaultInstance().getDebugMessage();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Error details (for debugging only)
       * </pre>
       *
       * <code>optional string debug_message = 15;</code>
       * @param value The bytes for debugMessage to set.
       * @return This builder for chaining.
       */
      public Builder setDebugMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        debugMessage_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:d_engine.error.ErrorMetadata)
    }

    // @@protoc_insertion_point(class_scope:d_engine.error.ErrorMetadata)
    private static final d_engine.error.Error.ErrorMetadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new d_engine.error.Error.ErrorMetadata();
    }

    public static d_engine.error.Error.ErrorMetadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ErrorMetadata>
        PARSER = new com.google.protobuf.AbstractParser<ErrorMetadata>() {
      @java.lang.Override
      public ErrorMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ErrorMetadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ErrorMetadata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public d_engine.error.Error.ErrorMetadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_d_engine_error_ErrorMetadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_d_engine_error_ErrorMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/error.proto\022\016d_engine.error\"\303\001\n\r" +
      "ErrorMetadata\022\033\n\016retry_after_ms\030\001 \001(\004H\000\210" +
      "\001\001\022\026\n\tleader_id\030\002 \001(\tH\001\210\001\001\022\033\n\016leader_add" +
      "ress\030\003 \001(\tH\002\210\001\001\022\032\n\rdebug_message\030\017 \001(\tH\003" +
      "\210\001\001B\021\n\017_retry_after_msB\014\n\n_leader_idB\021\n\017" +
      "_leader_addressB\020\n\016_debug_message*\326\003\n\tEr" +
      "rorCode\022\013\n\007SUCCESS\020\000\022\027\n\022CONNECTION_TIMEO" +
      "UT\020\351\007\022\024\n\017INVALID_ADDRESS\020\352\007\022\023\n\016LEADER_CH" +
      "ANGED\020\353\007\022\017\n\nJOIN_ERROR\020\354\007\022\025\n\020INVALID_RES" +
      "PONSE\020\321\017\022\025\n\020VERSION_MISMATCH\020\322\017\022\016\n\tDISK_" +
      "FULL\020\271\027\022\024\n\017DATA_CORRUPTION\020\272\027\022\025\n\020STORAGE" +
      "_IO_ERROR\020\273\027\022\036\n\031STORAGE_PERMISSION_DENIE" +
      "D\020\274\027\022\022\n\rKEY_NOT_EXIST\020\275\027\022\017\n\nNOT_LEADER\020\241" +
      "\037\022\024\n\017STALE_OPERATION\020\242\037\022\024\n\017INVALID_REQUE" +
      "ST\020\243\037\022\021\n\014RATE_LIMITED\020\244\037\022\030\n\023CLUSTER_UNAV" +
      "AILABLE\020\245\037\022\023\n\016PROPOSE_FAILED\020\246\037\022\022\n\rTERM_" +
      "OUTDATED\020\247\037\022\023\n\016RETRY_REQUIRED\020\250\037\022\014\n\007GENE" +
      "RAL\020\270E\022\022\n\rUNCATEGORIZED\020\217NB+Z)github.com" +
      "/deventlab/d-engine/proto/errorb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_d_engine_error_ErrorMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_d_engine_error_ErrorMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_d_engine_error_ErrorMetadata_descriptor,
        new java.lang.String[] { "RetryAfterMs", "LeaderId", "LeaderAddress", "DebugMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
